export const GET_PIXYL_LESIONS = 'GET_PIXYL_LESIONS';
export const LOADING_GET_PIXYL_LESIONS = 'LOADING_GET_PIXYL_LESIONS';
export const WAITING_PIXYL_ANALYSIS = 'WAITING_PIXYL_ANALYSIS';
export const WAITING_UPLOAD_SEGMENTATION = 'WAITING_UPLOAD_SEGMENTATION';
export const ERROR_GET_PIXYL_LESIONS = 'ERROR_GET_PIXYL_LESIONS';
export const SHOW_HIDE_SEGMENTATION = 'SHOW_HIDE_SEGMENTATION';
export const REMOVE_ADD_SEGMENT_SEGMENTATION =
  'REMOVE_ADD_SEGMENT_SEGMENTATION';
export const UNDO_REMOVE_ADD_SEGMENT_SEGMENTATION =
  'UNDO_REMOVE_ADD_SEGMENT_SEGMENTATION';
export const REDO_REMOVE_ADD_SEGMENT_SEGMENTATION =
  'REDO_REMOVE_ADD_SEGMENT_SEGMENTATION';
export const SET_MOUSE_OVER_INFOS = 'SET_MOUSE_OVER_INFOS';
export const SET_REMOVE_LESION_BY_MOUSE_CLICK =
  'SET_REMOVE_LESION_BY_MOUSE_CLICK';
export const SET_REMOVE_LESION = 'SET_REMOVE_LESION';
