export const GET_PIXYL_LESIONS = 'GET_PIXYL_LESIONS';
export const LOADING_GET_PIXYL_LESIONS = 'LOADING_GET_PIXYL_LESIONS';
export const WAITING_PIXYL_ANALYSIS = 'WAITING_PIXYL_ANALYSIS';
export const WAITING_UPLOAD_SEGMENTATION = 'WAITING_UPLOAD_SEGMENTATION';
export const ERROR_GET_PIXYL_LESIONS = 'ERROR_GET_PIXYL_LESIONS';
export const SHOW_HIDE_SEGMENTATION = 'SHOW_HIDE_SEGMENTATION';
